# Generated by Django 3.2.9 on 2021-12-08 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblQuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='问题类别名称', max_length=64)),
                ('tag', models.CharField(help_text='问题类别标签', max_length=32, unique=True)),
                ('description', models.CharField(blank=True, help_text='问题类别的描述', max_length=512, null=True)),
            ],
            options={
                'db_table': 'tbl_question_category',
            },
        ),
        migrations.CreateModel(
            name='TblQuestionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='题目难易度名称', max_length=64)),
                ('tag', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], help_text='问题类别标签', max_length=1, unique=True)),
                ('description', models.CharField(help_text='题目难易度的描述', max_length=128)),
            ],
            options={
                'db_table': 'tbl_question_level',
            },
        ),
        migrations.CreateModel(
            name='TblQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='选项的内容', max_length=512)),
                ('description', models.CharField(blank=True, help_text='选项的额外描述，可以用于题目答案解析', max_length=512, null=True)),
            ],
            options={
                'db_table': 'tbl_question_option',
            },
        ),
        migrations.CreateModel(
            name='TblQuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='问题类别名称', max_length=64)),
                ('tag', models.CharField(choices=[('S', 'Single'), ('M', 'Multiple'), ('J', 'Judge')], help_text='问题类别标签', max_length=1, unique=True)),
                ('description', models.CharField(blank=True, help_text='问题类别的描述', max_length=512, null=True)),
            ],
            options={
                'db_table': 'tbl_question_type',
            },
        ),
        migrations.CreateModel(
            name='TblQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='题目内容')),
                ('description', models.TextField(help_text='题目额外的描述')),
                ('option_ids', models.JSONField(blank=True, default=None, help_text='题目的选项，用选项的id用-连在一起表示答案', null=True)),
                ('anser_ids', models.JSONField(blank=True, default=None, help_text='题目的选项，用选项的id用-连在一起表示答案', null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('category_tag', models.ForeignKey(default='other', help_text='题目类型', on_delete=django.db.models.deletion.DO_NOTHING, to='question.tblquestioncategory', to_field='tag')),
            ],
            options={
                'db_table': 'tbl_question',
            },
        ),
    ]
