# Generated by Django 4.0 on 2021-12-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblquestion',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='题目创建者', on_delete=django.db.models.deletion.DO_NOTHING, to='users.userinfo'),
        ),
        migrations.AddField(
            model_name='tblquestion',
            name='level_tag',
            field=models.ForeignKey(default='E', help_text='题目难易度级别', on_delete=django.db.models.deletion.DO_NOTHING, to='question.tblquestionlevel', to_field='tag'),
        ),
        migrations.AddField(
            model_name='tblquestion',
            name='type_tag',
            field=models.ForeignKey(default='S', help_text='题目类型', on_delete=django.db.models.deletion.DO_NOTHING, to='question.tblquestiontype', to_field='tag'),
        ),
    ]
