# Generated by Django 3.2.9 on 2021-12-08 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='考试名称', max_length=128)),
                ('avatar', models.CharField(help_text='考试的预览图', max_length=256)),
                ('description', models.CharField(blank=True, help_text='考试描述', max_length=256, null=True)),
                ('score', models.IntegerField(default=0, help_text='当前考试的总分数', verbose_name='当前考试的总分数')),
                ('limit_time', models.IntegerField(default=0, help_text='考试时长')),
                ('start_date', models.DateTimeField(help_text='考试有效期开始时间')),
                ('end_date', models.DateTimeField(help_text='考试有效期结束时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'db_table': 'tbl_exam',
            },
        ),
        migrations.CreateModel(
            name='TblExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_options', models.JSONField(help_text='答案选项')),
            ],
            options={
                'db_table': 'tbl_exam_answer',
            },
        ),
        migrations.CreateModel(
            name='TblExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='考试分类名称', max_length=128)),
                ('tag', models.CharField(help_text='标签', max_length=32, unique=True)),
                ('description', models.CharField(blank=True, help_text='详细阐述', max_length=512, null=True)),
            ],
            options={
                'db_table': 'tbl_exam_category',
            },
        ),
        migrations.CreateModel(
            name='TblExamLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='考试难度名称', max_length=128)),
                ('tag', models.CharField(help_text='标签', max_length=32, unique=True)),
                ('description', models.CharField(blank=True, help_text='详细阐述', max_length=512, null=True)),
            ],
            options={
                'db_table': 'tbl_exam_level',
            },
        ),
        migrations.CreateModel(
            name='TblExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(default=0, help_text='得分')),
                ('time_cost', models.SmallIntegerField(default=0, help_text='耗时')),
                ('category_score', models.JSONField(default=dict, help_text='分类得分')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='开始时间')),
            ],
            options={
                'db_table': 'tbl_exam_record',
            },
        ),
        migrations.CreateModel(
            name='TblExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, help_text='题目分数')),
                ('exam', models.ForeignKey(help_text='考试', on_delete=django.db.models.deletion.CASCADE, to='exam.tblexam')),
            ],
        ),
    ]
