# Generated by Django 3.2.9 on 2021-12-08 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblexamsubject',
            name='question',
            field=models.ForeignKey(help_text='题目', on_delete=django.db.models.deletion.CASCADE, to='question.tblquestion'),
        ),
        migrations.AddField(
            model_name='tblexamrecord',
            name='exam',
            field=models.ForeignKey(db_constraint=False, help_text='考试ID', on_delete=django.db.models.deletion.DO_NOTHING, to='exam.tblexam'),
        ),
    ]
