# Generated by Django 4.0 on 2021-12-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('question', '0001_initial'),
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblexamrecord',
            name='joiner',
            field=models.ForeignKey(db_constraint=False, help_text='参与者ID', on_delete=django.db.models.deletion.DO_NOTHING, to='users.userinfo'),
        ),
        migrations.AddField(
            model_name='tblexamrecord',
            name='questions',
            field=models.ManyToManyField(help_text='题目', through='exam.TblExamAnswer', to='question.TblQuestion'),
        ),
        migrations.AddField(
            model_name='tblexamanswer',
            name='exam_record',
            field=models.ForeignKey(help_text='考试ID', on_delete=django.db.models.deletion.CASCADE, to='exam.tblexamrecord'),
        ),
        migrations.AddField(
            model_name='tblexamanswer',
            name='question',
            field=models.ForeignKey(db_constraint=False, help_text='题目ID', on_delete=django.db.models.deletion.DO_NOTHING, to='question.tblquestion'),
        ),
        migrations.AddField(
            model_name='tblexam',
            name='creater',
            field=models.ForeignKey(db_constraint=False, help_text='创建考试的用户', on_delete=django.db.models.deletion.DO_NOTHING, to='users.userinfo'),
        ),
    ]
